concurrency:
  cancel-in-progress: true
  group: ${{ (github.ref == 'refs/heads/master') && format('ci-main-{0}', github.sha)
    || format('ci-main-{0}', github.ref) }}
env:
  USE_BAZEL_VERSION: 7.1.1
  USE_JAVA_DISTRIBUTION: zulu
  USE_JAVA_VERSION: '11'
jobs:
  bazel-build:
    name: Bazel Build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: ./.github/actions/bazel-build
  bazel-test:
    name: Test using Bazel with JDK ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: ./.github/actions/bazel-test
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 17
          os: macos-latest
        java:
        - 11
        - 17
        - 21
        os:
        - ubuntu-latest
      max-parallel: 4
  local-artifact-tests:
    name: Local Artifact Tests
    needs:
    - bazel-build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: ./.github/actions/local-artifact-tests
  maven-test:
    name: Test using Maven with JDK ${{ matrix.java }} on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: ./.github/actions/maven-test
    strategy:
      fail-fast: false
      matrix:
        include:
        - java: 17
          os: macos-latest
        java:
        - 11
        - 17
        - 21
        os:
        - ubuntu-latest
      max-parallel: 4
  publish:
    if: github.event_name == 'push' && github.repository == 'google/guice' && github.ref
      == 'refs/heads/master'
    name: Publish Javadoc and Snapshot
    needs:
    - maven-test
    - bazel-test
    - bazel-build
    - local-artifact-tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      uses: ./.github/actions/publish-snapshot
name: continuous-integration
on:
  repository_dispatch:
    types: trigger-ga___ci.yml
